### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by albinekcom**
This commit contains optimized images (the same quality, smaller sizes).

### CODE REVIEW

**Comment by zawadz88** [comment]
Sorry Albin, already optimized ;)

**Comment by albinekcom** [comment]
I rebased my branch with the newest `master` and optimized images once again.

There are the results:
Previously: `~307 KB`
Currently: `~255 KB`
Saved: `~52 KB (~17%)`

So sorry @zawadz88, I can't agree with you. 😉

**Comment by zawadz88** [comment]
Daj re-open ;)

**Comment by albinekcom** [comment]
Done. Link: https://github.com/zawadz88/MaterialPopupMenu/pull/20. 🙂

**Pull request closed without merging**
