### PR TITLE
fix context theme modification

### PR DESCRIPTION
**Pull request by plshapkin**

### CODE REVIEW

**Comment by zawadz88** [comment]
Hi @plshapkin,
Thanks for the commit but could you please explain what's the issue and how to reproduce it?

**Comment by plshapkin** [comment]
Hi. When you call ContextThemeWrapper(context, context.theme) wrapper don't create new theme. So call contextThemeWrapper.setTheme(style) modifies context.theme.
Your style Widget.MPM.Menu has parent Widget.AppCompat.PopupMenu.Overflow and inherit parent attributes. When you set this style to context.theme you change many attributes in context.theme like popup background.

**Comment by vsumtsov-gh** [comment]
Hi. Looks like we have similar issue on android 8. As toolbar background, we use             android:background="?colorPrimary". After popup showing, this theme attribute color redifines and toolbar changes background in all app.

**Comment by VladSumtsov** [comment]
Hi. Looks like we have similar issue on android 8. As toolbar background, we use android:background="?colorPrimary". After popup showing, this theme attribute color redifines and toolbar changes background in all app.

**Comment by zawadz88** [comment]
Hi @plshapkin @VladSumtsov 
So this is actually intentional (at least partially). The intention here is to be able to override the default Activity theme allowing you to e.g. to use a dark popup menu in an Activity with a Light theme and have a correct popup item background selector when clicked.
This was introduced to solve: https://github.com/zawadz88/MaterialPopupMenu/issues/12

After applying the fix from this PR the background selector in the sample app does not work as expected though...

The selector is defined in `styles.xml`:
```
<style name="Widget.MPM.Item" parent="">
    <item name="android:background">?android:attr/listChoiceBackgroundIndicator</item>
</style>
```

After the fix `listChoiceBackgroundIndicator` from the Activity is used and not from theme set via `mpm_theme` in `Widget.MPM.Menu.Dark`.
In the sample app you can check this by going to Dark Activity/Light Activity sample, clicking "Custom colors" and long clicking on a popup menu item.

What's not intended is the situation described by @VladSumtsov :/
I'll have a look, however if you guys have any ideas on how to account for the above I'm all ears :)

Thanks for contributing

**Comment by zawadz88** [comment]
Scratch the above remark around:
>This was introduced to solve: #12
Setting themes was actually from the beginning...

Anyway, I think I've found a quick workaround however I'll need some time to test this properly.

**Comment by zawadz88** [comment]
Hi @plshapkin @VladSumtsov,
Thanks for reporting this and the explanations!
Could you guys have a look at the version proposed in #19?
This contains the fix added by @plshapkin but also fixes the background selector issue.
It also contains a library version update so that it can be uploaded to a Maven repo and distributed.

**Comment by zawadz88** [comment]
Released in 2.0.0

**Pull request merged**
